### ISSUE TITLE
PHP Error when submitting a form

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-gravity-forms#53]
Im seeing this error when submitting a form

````
[07-Apr-2021 17:26:29 UTC] PHP Fatal error:  Uncaught Exception: Event with code 5709 has not be registered. in /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php:407
Stack trace:
#0 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php(403): WSAL_AlertManager->_CommitItem(5709, Array, NULL, false)
#1 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php(291): WSAL_AlertManager->_CommitItem(5709, Array, NULL)
#2 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/activity-log-gravity-forms-master/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php(1225): WSAL_AlertManager->Trigger(5709, Array)
#3 /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-includes/class-wp-hook.php(294): WSAL_Sensors_Gravity_Forms->event_form_submitted(Array, Array)
#4 /var/www/daniel.wpwhitesecur in /var/www/daniel.wpwhitesecurity.net/main/public_html/wp-content/plugins/wp-security-audit-log-premium-develop/classes/AlertManager.php on line 40

````

**Comment by DannyWPWS** [comment]
Closing this up as iv been unable to re-trigger it during testing
