### ISSUE TITLE
[8585] - PHP error when creating confirmation

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/activity-log-gravity-forms#95]
https://secure.helpscout.net/conversation/1934582638/8585?folderId=4248868

We are seeing this when creating events and using WSAL 4.4.2

`
[29-Jun-2022 15:53:57 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WSAL_Sensors_Gravity_Forms::trigger_event_if(), 2 passed in /Users/newuser/Local Sites/wsal-premium/app/public/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php on line 936 and exactly 3 expected in /Users/newuser/Local Sites/wsal-premium/app/public/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php:1493
Stack trace:
#0 /Users/newuser/Local Sites/wsal-premium/app/public/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php(936): WSAL_Sensors_Gravity_Forms->trigger_event_if(5705, Array)
#1 /Users/newuser/Local Sites/wsal-premium/app/public/wp-includes/class-wp-hook.php(309): WSAL_Sensors_Gravity_Forms->event_form_confirmation_saved(Array, Array, true)
#2 /Users/newuser/Local Sites/wsal-premium/app/public/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array) in /Users/newuser/Local Sites/wsal-premium/app/public/wp-content/plugins/activity-log-gravity-forms/wp-security-audit-log/custom-sensors/WSAL_Sensors_Gravity_Forms.php on line 1493
`

**Comment by DannyWPWS** [comment]
This PR also fixes https://github.com/wpwhitesecurity/activity-log-gravity-forms/issues/97
